config/routes.rb
ParraPuma::Application.routes.draw do
  resources :regalos

  root :to => 'regalos#index'

  namespace :admin do
    resources :regalos
  end

end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :regalo
end

app/models/regalo.rb
class Regalo < ActiveRecord::Base
  has_many :productos, :dependent => :destroy
  accepts_nested_attributes_for :productos, :allow_destroy => true, :reject_if => proc { |attributes| attributes['url'].blank? }

  validate do |regalo|
    errors.add(:base, "Ya esta reservado") if reservado?
  end
  after_validation :guardar_reservado

  def guardar_reservado
    if self.email_amigo.blank? or self.nombre_amigo.blank?
      self.email_amigo = self.nombre_amigo = nil
      self.reservado = false
    else
      self.reservado = true
    end
  end
end

app/controllers/admin/regalos_controller.rb
class Admin::RegalosController < ApplicationController
  before_filter :authentication_check

  def index
    @regalos = Regalo.all
  end

  def create
    @regalo = Regalo
  end

  def edit
    @regalo = Regalo.find params[:id], :include => :productos
    10.times { @regalo.productos.build }  
  end
  
  def update
    @regalo = Regalo.find params[:id]
    @regalo.update_attributes params[:regalo]
    redirect_to :action => :index
  end

  def new
    @regalo = Regalo.new
    10.times { @regalo.productos.build }  
  end

  def create
    Regalo.create params[:regalo]
    redirect_to :action => :index
  end

  def destroy
    Regalo.find(params[:id]).destroy
    redirect_to :action => :index
  end

  private
  def authentication_check
    authenticate_or_request_with_http_basic do |user, password|
      user == 'parrapuma' && password == 'joloijolito'
    end
  end
end

app/controllers/admin_controller.rb
class Admin::RegalosController < ApplicationController
  def index
    @regalos = Regalo.all
  end

  def create
    @regalo = Regalo
  end

  def edit
    @regalo = Regalo.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/regalos_controller.rb
class RegalosController < ApplicationController
  def index
    @regalos = Regalo.includes(:productos).where('nombre is not NULL')
  end

  def update
    regalo = Regalo.find params[:id]
    if regalo.reservado?
      render :text => 'Error: ya reservado', :status => 403 and return
    end
    if regalo.update_attributes params[:regalo] and regalo.reservado?
      render :text => 'OK', :status => 200
    else
      render :text => 'Error: campo vacio', :status => 400 
    end
  end

  def create
    if Regalo.create params[:regalo]
      render :text => 'ok', :status => 200
    else
      render :text => 'error: campo vacio', :status => 400
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/regalos/edit.html.erb
<%= form_for @regalo, :url => admin_regalo_path(@regalo) do |f| %>
  <p>Nombre <%= f.text_field :nombre %></p>
  <p>Descripción <%= f.text_field :descripcion %></p>
  <p>Precio <%= f.text_field :precio %></p>
  <p>Reservado <%= f.text_field :reservado? %></p>
  <p>Nombre amigo <%= f.text_field :nombre_amigo %></p>
  <p>Email amigo <%= f.text_field :email_amigo %></p>
  <p>Comentario <%= f.text_area :comentario, :rows => 5 %></p>
  <%= f.fields_for :productos do |p| %>
    <p>URL <%= p.text_field :url %>, cantidad <%= p.text_field :cantidad %> Eliminar <%= p.check_box :_destroy %></p>
  <% end %>
  <p><%= f.submit 'Guardar' %></p>
<% end %>

app/views/admin/regalos/index.html.erb
<style type='text/css'>
  table {border: solid 1px;}
  td {border: solid 1px;}
</style>
<table>
  <tr>
    <th>Nombre</th>
    <th>Descripción</th>
    <th>Precio</th>
    <th>Reservado</th>
    <th>Nombre amigo</th>
    <th>Email amigo</th>
    <th></th>
  </tr>
  <% @regalos.each do |r| %>
    <tr>
      <td><%= r.nombre %></td>
      <td><%= r.descripcion %></td>
      <td><%= r.precio %></td>
      <td><%= r.reservado? %></td>
      <td><%= r.nombre_amigo %></td>
      <td><%= r.email_amigo %></td>
      <td><%= r.comentario %></td>
      <td>
        <%= link_to 'Editar', edit_admin_regalo_path(r) %>
        <%= link_to 'Eliminar', admin_regalo_path(r), :method => :delete, :confirm => 'Yeah?' %>
      </td>
    </tr>
  <% end %>
</table>
<%= link_to 'Nuevo', new_admin_regalo_path %>

  

app/views/admin/regalos/new.html.erb
<%= form_for @regalo, :url => admin_regalos_path do |f| %>
  <p>Nombre <%= f.text_field :nombre %></p>
  <p>Descripción <%= f.text_field :descripcion %></p>
  <p>Precio <%= f.text_field :precio %></p>
  <%= f.fields_for :productos do |p| %>
    <p>URL<%= p.text_field :url %>, cantidad <%= p.text_field :cantidad %></p>
  <% end %>
  <p><%= f.submit 'Guardar' %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParraPuma</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.form" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/regalos/index.html.erb
<style>
  .bienvenido {
    font-family: 'lucida grande', tahoma, verdana, arial, sans-serif;
    width:670px;
    font-size: 13px;
    margin:20px auto;
    padding:15px;
  }
  .bienvenido.ingles {
    display:none;
  }
  .regalo {
    background-color: #3B5998;
    border: 1px solid #1D4088;
    color: white;
    font-family: 'lucida grande', tahoma, verdana, arial, sans-serif;
    width:670px;
    font-size: 14px;
    margin:20px auto;
    padding:15px;
  }
  .reserva {
    display:none;
    padding:10px;
    margin:20px 10px 5px;
    background-color: #627AAD;
    border: 1px solid #1D4088;
  }
  a {
    color:#ddd;
  }
  a.cambiar-idioma {
    color: #222;
  }
  .estado-reserva {
    margin-top:10px;
    font-size:12px;
  }
  .links-reserva {
    text-align:right;
    margin-top:5px;
  }
  .descripcion {
    font-size:13px;
    margin-top:3px;
  }
  .links {
    float:right;
  }
  .precio {
    float:right;
    margin-top:3px;
  }
</style>

<%= image_tag 'banner.png', :style => 'margin:20px auto; display:block;' %>

<div class="bienvenido espanol">
  <p>Hola, esta es nuestra Lista de Novios. Acá encontrarás un lista de cosas que necesitamos y que puedes usar como una guía en el caso que nos quieras hacer un regalo. Cada regalo tiene una descripción y links para ver exactamente qué nos estas regalando. El costo del regalo es un aproximado del precio, impuestos y costos de envío. Para reservar un regalo, sólo has click en "Reservar", ingresa tu nombre y email, luego nosotros te contactaremos. Si te gusta un ítem especifico pero se aleja de tu presupuesto, ten la confianza de agruparte con otros amigos y hacer un regalo en conjunto.</p> 
  <p>Por último, si quieres regalarnos algo que no está en la lista y no sabes como hacérnoslo llegar, o necesitas información de nuestras cuentas bancarias, por favor anda a "Otro regalo" y agrega ahí tu información.</p> 
  <p>Muchas Gracias</p>
  <p>Javi &amp; Álvaro</p>
  <%= link_to 'View in English', '', {'class' => 'cambiar-idioma', 'data-idioma' => 'ingles'} %>
</div>

<div class="bienvenido ingles">
  <p>Hi, this is our Wedding Registry. Here you'll find a list of things we need and which you may use as guidance in case you want to give us a present. Each gift has a description and links so you'll know exactly what you are giving us. The price of the gift is an approximate of its costs, taxes and shipping. To reserve a gift just click "Reserve," add your name and email, then we will contact you. If you really like a gift but its out of your budget, feel free to group with other people and give it as a group gift.</p>
  <p>Finally, if you have another gift in mind and you don't know how to send it to us or if you need our bank account info, please go to "Other Gifts" and add your information there.</p>
  <p>Thanks!</p>
  <p>Javi & Álvaro</p>
  <%= link_to 'Ver en español', '', {'class' => 'cambiar-idioma', 'data-idioma' => 'espanol'} %>
</div>

<% @regalos.each do |regalo| %>
  <div class="regalo">
    <div class="links">
      Links:
      <% regalo.productos.each_with_index do |p,i| %>
        <%= link_to (i+65).chr, p.url, {:target => '_blank'} -%><%= "×#{p.cantidad}" if p.cantidad -%><%= "," if i<regalo.productos.size-1 %>
      <% end %>
    </div>
    <div><%= regalo.nombre %> </div>
    <div class="precio">USD <%= regalo.precio %> </div>
    <div class="descripcion"><%= regalo.descripcion %></div>
    <div class="estado-reserva">
      <% if regalo.reservado? %>
        Este regalo ya fue reservado
      <% else %>
        <%= link_to 'Reservar/Reserve', '', {'class' => 'reservar'} %>
      <% end %>
      <%= form_for regalo, :html => {:class => 'reserva'} do |f| %>
        Nombre/Name <%= f.text_field :nombre_amigo %>
        Email <%= f.text_field :email_amigo %>
        <br>
        Comentario/Comment <br> <%= f.text_area :comentario, :rows => 3 %>
        <div class="links-reserva">
          <%= link_to 'Cancelar/Cancel', '', {'class' => 'cancelar'} %> | 
          <%= link_to 'Confirmar/Confirm', '', {'class' => 'enviar-reserva'} %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<div class="regalo">
  <div>Other Gift / Otro Regalo</div>
  <div class="descripcion">
    <p>Use this category if you have another gift in mind and you don't know how to send it to us or if you need our bank account info. Use the comments section below to specify.</p>
      <p>Usa esta categoría si quieres regalarnos algo que no está en la lista y no sabes como hacérnoslo llegar, o si necesitas información de nuestras cuentas bancarias. Puedes usar la sección de comentarios para poner detalles específicos.</p>
  </div>
  <div class="estado-reserva">
    <%= link_to 'Reservar/Reserve', '', {'class' => 'reservar'} %>
    <%= form_for :regalo, :html => {:class => 'reserva'} do |f| %>
      Nombre/Name <%= f.text_field :nombre_amigo %>
      Email <%= f.text_field :email_amigo %>
      <br>
      Comentario/Comment <br> <%= f.text_area :comentario, :rows => 3 %>
      <div class="links-reserva">
        <%= link_to 'Cancelar/Cancel', '', {'class' => 'cancelar'} %> | 
        <%= link_to 'Confirmar/Confirm', '', {'class' => 'enviar-reserva'} %>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(function(){

    $('a.reservar').click(function(){
      $(this).siblings('form.reserva').show();
      return false;
    });

    $('form.reserva a.cancelar').click(function(){
      $(this).parents('form.reserva').hide();
      return false;
    });

    $('a.enviar-reserva').click(function(e){
      var $form = $(this).parents('form');
      $form.ajaxSubmit({
        success:function(){
          $form.hide();
          var $link = $form.parents('.regalo').find('a.reservar');
          $link.after('Este regalo ya fue reservado');
          $link.remove();
          alert('¡Has reservado este regalo!');
        },
        statusCode: {
          403:function(){
            $form.hide();
            var $link = $form.parents('.regalo').find('a.reservar');
            $link.after('Este regalo ya fue reservado');
            $link.remove();
            alert('El regalo ya fue reservado; busca otro.');
          },
          400:function(){
            $form.hide();
            alert('No ingresaste tu nombre o email; intenta de nuevo.');
          }
        }
      });
      return false;
    });

    $('a.cambiar-idioma').click(function(e){
      $('.bienvenido').hide();
      $('.bienvenido.'+$(this).data('idioma')).show();
      return false;
    });

  });
</script>